### ISSUE TITLE
Failing on AppVeyor

### ISSUE THREAD

**Issue by mem48** [ropensci/opentripplanner#18]
It seems to be a problem with geodist

```
Installing 1 packages: geodist
Installing package into 'c:/RLibrary'
(as 'lib' is unspecified)
  There is a binary version available but the source version is later:
        binary source needs_compilation
geodist  0.0.2  0.0.3              TRUE
installing the source package 'geodist'
trying URL 'https://cran.rstudio.com/src/contrib/geodist_0.0.3.tar.gz'
Content type 'application/x-gzip' length 536443 bytes (523 KB)
==================================================
downloaded 523 KB
* installing *source* package 'geodist' ...
** package 'geodist' successfully unpacked and MD5 sums checked
** libs
*** arch - i386
c:/Rtools/mingw_32/bin/gcc  -I"c:/R/include" -DNDEBUG          -O3 -Wall  -std=gnu99 -mtune=generic -c common.c -o common.o
/bin/sh: c:/Rtools/mingw_32/bin/gcc: No such file or directory
make: *** [common.o] Error 127
ERROR: compilation failed for package 'geodist'
* removing 'c:/RLibrary/geodist'
* restoring previous 'c:/RLibrary/geodist'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package 'geodist' had non-zero exit status
Calls: <Anonymous> ... with_rprofile_user -> with_envvar -> force -> force -> i.p
Execution halted
Command exited with code 1
```

**Comment by mem48** [comment]
@mpadge is this a problem with the geodist package itself? As far as I can tell there where no problems with 0.0.2

**Comment by mpadge** [comment]
Ah yeah, could well be. 0.0.2 had intermittent problems with DLL linking, so I implemented a solution this week on 0.0.3 that I thought solved it, but.... I'll investigate further and get back to you

**Comment by mpadge** [comment]
@mem48: Can you try now with `Remotes: hypertidy/geodist` in your `DESCRIPTION` file to load current github rather than CRAN version?

**Comment by mem48** [comment]
I've pushed the change to the wip branch https://github.com/ITSLeeds/opentripplanner/commit/a7c36017b4106e4000391c021dc3b99bb403d822

**Comment by mem48** [comment]
It still seems to be failing :(

**Comment by mpadge** [comment]
I don't think `geodist` is causing this. I set up a test repo [here](https://github.com/mpadge/gdtest), which depends on geodist, and passes both on travis and appveyor. The key line in your output is,
> Package geodist has compiled code, but no suitable compiler(s) were found. Installation will likely fail

In the output you pasted above, it's
> c:/Rtools/mingw_32/bin/gcc  -I"c:/R/include" -DNDEBUG          -O3 -Wall  -std=gnu99 -mtune=generic -c common.c -o common.o
/bin/sh: c:/Rtools/mingw_32/bin/gcc: No such file or directory

It is `gcc` that is not being found, and that is needed to compile and install `geodist`. You're missing the following lines in your `appveyor.yml`, which were generated in [`gdtest`](https://github.com/mpadge/gdtest) with `usethis::use_appveyor`:
```
environment:
  NOT_CRAN: true
  # env vars that may need to be set, at least temporarily, from time to time
  # see https://github.com/krlmlr/r-appveyor#readme for details
  # USE_RTOOLS: true
  # R_REMOTES_STANDALONE: true
```
The problem is arising because the appveyor machine is trying and failing to install RTools. On my test repo, this is not installed because there is no `/src` code, but you've got no `/src` either, so need to investigate that any further. All you have to do is stop `RTools` from trying - failing! - to install, which must simply be the line:
```
environment:
  NOT_CRAN: true
```

**Comment by mem48** [comment]
@mpadge I've updated the appveyor.yml but it is still failing

**Comment by mem48** [comment]
Ah, It works now I've removed the remotes, thanks
