### ISSUE TITLE
Overlong load time in otp_setup

### ISSUE THREAD

**Issue by lgaa320** [ropensci/opentripplanner#65]
Hello again, and sorry for opening another issue. Problem this time is that OTP is taking an extremely long time to set up. The message received is: 
```
2020-06-15 14:29:16 OTP is loading and may take a while to be useable
2020-06-15 14:47:57 OTP is taking an unusually long time to load, releasing R to your control, OTP will continue in the background
```

My code is:

```
path_data <- file.path("[]/Documents/[]", "OTP")
path_otp <- file.path("[]/Documents/[]/OTP/otp.jar")
log1 <- otp_build_graph(otp = path_otp, dir = path_data, router = "NYC", memory = 54000)
log2 <- otp_setup(otp = path_otp, dir = path_data, router = "NYC")
```
And my file structure looks like:

[img]https://i.imgur.com/axXkMZs.png[/img]

Thanks so much.

**Comment by mem48** [comment]
So as it says in the [documentation](https://docs.ropensci.org/opentripplanner/reference/otp_setup.html) `otp_setup` will only wait 5 minutes before releasing control of R.

You have a large graph of 0.8 GB so it is possible that you simply need to wait longer. Look in task manager and see if Java is still using CPU.

![image](https://user-images.githubusercontent.com/15819577/84946464-af64c080-b0e0-11ea-98ab-2f11db610a9e.png)

If it is,just wait until Java is using no CPU an then run `otp_connect`  if that doesn't work then java is probably crashing, usually, because you don't have enough RAM

**Comment by mem48** [comment]
I noticed you set 54GB of memory to build the graph but are using the default 2GB to run otp. If you needed 54 GB it is unlikely to run in just 2GB.
